### ISSUE TITLE
getSymbols.oanda HTTP error 404

### ISSUE THREAD

**Issue by MihalisPapatsimpas** [joshuaulrich/quantmod#225]
I try to get some symbols from Oanda and I can't.  I have tried also Google and Yahoo and the result is the same.  I try to execute the following and what I get is an error.

```r
eurusd  <-  getSymbols("EUR/USD", src = "oanda", auto.assign = FALSE)
Error in open.connection(con, "rb") : HTTP error 404.
```

**Comment by joshuaulrich** [comment]
Thanks for the report.  I can replicate.

Google no longer provides price data.  I checked Yahoo Finance and they specify the EUR/USD pair as [EURUSD=X](https://finance.yahoo.com/quote/EURUSD=X), so `getSymbols("USDEUR=X", src = "yahoo")` works.

**Comment by MihalisPapatsimpas** [comment]
Thanks for the reply. 

Yes,now I can get from Yahoo. But,what about oanda? I still can't use getSymbols with oanda. Is it maybe because oanda v1 REST API will cease to function?

**Comment by joshuaulrich** [comment]
@MihalisPapatsimpas I just pushed a branch that works for me.  Please test to see if it works for you too!

**Comment by MihalisPapatsimpas** [comment]
Thank you @joshuaulrich for your help! To test it,I installed the quantmod package from your repository using the following: devtools::install_github("joshuaulrich/quantmod"). The error still appears. Is this the right way to test it? 

Thanks again!

**Comment by joshuaulrich** [comment]
No, that will just pull the current HEAD of master.  My patch is on the branch 225_getsymbols_oanda.  I think you can pull and install that via: `devtools::install_github("joshuaulrich/quantmod", ref="225_getsymbols_oanda")`.  If that doesn't work, please read the devtools docs or search on Google and/or StackOverflow.  I don't use devtools, so I won't be much help.

**Comment by MihalisPapatsimpas** [comment]
I installed the patch in 2 ways. The one you suggested and with: 
`githubinstall : : gh_install_packages("quantmod",ref` = "225_getsymbols_oanda")`. Both work but the error remains.

**Comment by joshuaulrich** [comment]
Is it exactly the same error?  I just tried on a different machine and got "HTTP error 400".  400 is "bad request", and 404 is "not found".

**Comment by MihalisPapatsimpas** [comment]
No,sorry i didn't mention it. It is "Error in open.connection(con, "rb") : HTTP error 400" .

**Comment by joshuaulrich** [comment]
I just pushed an update that corrects a mistake I made.  It works for me now, I promise. :)

**Comment by MihalisPapatsimpas** [comment]
Yes, now it works perfect!!

Thanks for your time!
